
// This file is a mapping for assets-map.json generated by webpack,
// configured in ./webpack.conf.json, to make Typescript Compiler happy

declare interface AssetsMap{
    [key: string]: {js: string};
}
declare const AssetsMap : AssetsMap;
export default AssetsMap;
