
// import them for a naive web server
import http = require ('http');
import fs = require('fs');

// the demo page
import Page from './page';

// import for configuring the render function
import RenderBuilder from '../renderer';

// Import the assets map generated by webpack, so we know the real URLs of the bundled scripts
import assetsMap = require('./assets-map');


let renderer = new RenderBuilder().setBundledAssetsMap((x)=> assetsMap[x].js ).build();

let server = http.createServer((req, res)=> {
    if (req.url == '/') {
        // Return rendered page
        res.statusCode = 200;
        res.end(renderer(Page, {
            title: 'test',
            data: {
                clock: new Date().toISOString()
            }
        }));
    } else {
        // Return script-bundle in the assets dir, in real-world application
        // you should use a static file serving component such to do this
        let outputStream =  fs.createReadStream('.'+req.url);
        outputStream.on('open', ()=> {
            res.statusCode = 200;
            res.setHeader('content-type', 'application/javascript');
            outputStream.pipe(res);
        })
    }

}).listen(0, 'localhost', () => {
    // Listen on random port and display the actual address this demo server is listen to
    console.log('server started at http://%s:%s/', server.address().address, server.address().port);
});